# These contents should not be considered
# authoritative for any real entity or business.
# 

[METADATA]
modified = 2021-09-21T00:00:00.000Z
#expires = 2019-03-01T00:00:00.000Z

[[VALIDATORS]]

[[ACCOUNTS]]
address = "rE3BGaHdGfMYF5kXsWkkiV7DUyr7aRXKGF"
desc = "UNIQUE DIGITAL PRIZE"

[[SERVERS]]
json_rpc = "https://s1.ripple.com:51234/"
ws = "wss://s1.ripple.com/"
peer = "https://s1.ripple.com:51235/"
desc = "General purpose server cluster"

[[PRINCIPALS]]
name = "STREAM" # Primary spec author
email = "streamb1ock320@gmail.com" 


[[CURRENCIES]]
code = "STREAM"
issuer = "rE3BGaHdGfMYF5kXsWkkiV7DUyr7aRXKGF"
network = "mainnet"
display_decimals = 2
symbol = "S" 


# End of file
